### PR TITLE
it looks better trust me

### PR DESCRIPTION
**Pull request by cck7202**
it looks better trust me :>:<

### CODE REVIEW

**Comment by cck7202** [comment]
it just does look better because blue is way better than yellow. Yellow is a bland color!  👍

**Comment by DMN2001** [comment]
No yellow is better

**Comment by cck7202** [comment]
NO BLUE IS BETTER!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by DMN2001** [comment]
what ever.

**Comment by cck7202** [comment]
you know its true

**Comment by DMN2001** [comment]
No its not trust me.

**Pull request closed without merging**
